name: Build (Frontend)

on:
  push:
    paths:
      - 'agent-starter-react-main/**'
  pull_request:
    paths:
      - 'agent-starter-react-main/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent-starter-react-main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint || true

      - name: Build
        run: pnpm build
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL || 'wss://example.livekit.cloud' }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY || 'dummy' }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET || 'dummy' }}
